### PR TITLE
Reduced waiting time at the exit from recommendation script

### PR DESCRIPTION
**Pull request by matke-84**
I already left a comment that there is some delay when exiting from recommended window. With this it is reduced. #897

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Oh, it's that delay you're talking about.

The delay is necessary to make sure that the info dialog has closed properly. If the info dialog is still active, it will block Kodi from closing the underlying custom window and you will get stuck on an empty screen.

The reason it needs to be 1 second is because sometimes the executebuiltin command will be delayed due to a WindowClose animation firing. Most of the time 0.1 will be fine, but you'll end up getting stuck with this shorter delay.

A different solution is needed here to ensure that the dialog has properly closed first.

**Comment by matke-84** [comment]
Yes, we need a solution here. The delay is a bit annoying. In AH2, it's not so noticeable because you have animations, and in my skin (titan bingie mod) it goes without animation, so it's really noticeable.
I also tried to solve the other problem from that post, when I use 'oninfo' takes me back to home.
`executebuiltin('Action(Info)') if self._recommendations == 'oninfo' else None`
And this actually works fine until I open the recommended window from the oninfo dialog. Then it returns me to home again. Here, too, it would be nice to we find some an elegant solution.

**Comment by jurialmunkey** [comment]
There is no good solution for the second. There is no way to retrieve the existing listitem from the info dialog in order to save it to the history. Simulating pressing info is not a good idea as it can very easily break if the timing is wrong.

You'll notice when back tracking via normal method that the last info dialog is not actually the one you opened if it was from the library - instead you get tmdbs online version of the same item (eg it will be same movie butmight have different artwork from TMDb instead of the library). That's because it's not possible to retrieve the listitem itself to reopen the dialog on - it can only save the ID and then reconstruct a listitem using online info.

**Comment by matke-84** [comment]
Ok. Certainly, it should not be complicated more than necessary. Stable work is more important. I'm going to keep this way of opening the list for now (cast in movies, cast in tv shows...), I'm just going to reduce a little bit the number of contents that it opens from 50 to maybe 30 in order to speed up a little bit of opening. I hope that you will find a solution to somehow eliminate that annoying delay when exiting from recommendation script.

**Comment by matke-84** [comment]
Any progress with this? 🙂

**Comment by davinciicodes** [comment]
@matke-84, if this is really urgent, I would recommend you submit another PR with a solution adapted to your needs and @jurialmunkey will review.

**Comment by matke-84** [comment]
There is probably a reason why @jurialmunkey  hasn't solved this problem yet, unless he forgot. 🙂
I hope that a solution will be found soon.

**Pull request closed without merging**
