### PR TITLE
Rewrite msgctxt #32481

### PR DESCRIPTION
**Pull request by dm1tz**
Also, update strings.po uk_ua.

### CODE REVIEW

**Comment by dm1tz** [comment]
The original version seems a bit elusive to me. Hope that the edit makes sense.

**Comment by jurialmunkey** [comment]
Yep change makes sense. Just need to escape the quotes around "Because you watched" in the msgid.

**Comment by dm1tz** [comment]
> Yep change makes sense. Just need to escape the quotes around "Because you watched" in the msgid.

Escaping the quotes is optional I believe. The [gettext manual](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) states:
```
The two strings, untranslated and translated, are quoted in various ways in the PO file, 
using " delimiters and \ escapes, but the translator does not really have to pay attention 
to the precise quoting format, as PO mode fully takes care of quoting for her.
```
Also, I haven't noticed any errors or warnings in the Kodi log. But still can do it if you want.

**Comment by jurialmunkey** [comment]
That's talking about breaking the string over multiple lines which doesn't matter how you do it as po just joins it all back together.

But if you want to use a double quote *inside* the string then you should escape it to make sure it displays correctly and is not read as an enclosing string character.

**Comment by dm1tz** [comment]
> That's talking about breaking the string over multiple lines which doesn't matter how you do it as po just joins it all back together.
> 
> But if you want to use a double quote _inside_ the string then you should escape it to make sure it displays correctly and is not read as an enclosing string character.

Thanks for the clarifications.

**Pull request merged**
