### PR TITLE
Dutch Language 

### PR DESCRIPTION
**Pull request by djdirty60**

### CODE REVIEW

**Comment by drinfernoo** [comment]
You removed Italian? 🤔

**Comment by djdirty60** [comment]
Did something go wrong, but you can only take over the folder and put it in your own addon?

**Comment by djdirty60** [comment]
English and Italian have been added

**Comment by drinfernoo** [comment]
English and Italian are already present in the add-on... and you've named the `language` folder as `Language`, capitalized. I would attempt to *only* add your Dutch translation, in the proper folder structure, without other changes.

**Pull request closed without merging**
