### PR TITLE
add no_folder player option

### PR DESCRIPTION
**Pull request by L2501**
no_folder player option for players that return one playable item via setResolvedUrl

### CODE REVIEW

**Comment by jurialmunkey** [comment]
What's the use case for this action? Why is this step necessary? If the path only returns one item and no further actions are defined, then the player will play the file.

The only time I could see this being useful is if the item return has the isFolder flag set to True. And in that case, it shouldn't be playable because it is a folder...

**Comment by jurialmunkey** [comment]
For instance, Youtube uses setResolveUrl and I can play the first item returned without a problem using this:
```
"play_movie"        : [
                        "plugin://plugin.video.youtube/search/?q={name}&search_type=notvalid",
                        {"position": "1"}
                      ],
```

**Comment by L2501** [comment]
/search/ returns a folder not a playable item

a playable item is `plugin://plugin.video.youtube/play/?video_id=dQw4w9WgXcQ` for example

**Comment by jurialmunkey** [comment]
> 
> 
> /search/ returns a folder not a playable item
> 
> a playable item is `plugin://plugin.video.youtube/play/?video_id=dQw4w9WgXcQ` for example

You can already play a path like this using
`"play_movie" : "plugin://plugin.video.youtube/play/?video_id=dQw4w9WgXcQ"`

I tested a youtube path like that already and it works completely fine on my end. The xbmc player can take either a plugin url that needs to be resolved or the actual resolved filepath - both are accepted.

**Comment by jurialmunkey** [comment]
BTW you realise that there is a difference between using `search_movie` and `play_movie`? 
Play movie expects a resolvable url where as search expects a folder.

**Comment by L2501** [comment]
i see, wiki should be then

|Key|Description|
|---|---|
|play_movie | movie plugin url passed to `RunPlugin(url)` if list or `PlayMedia(url)` if string|
|play_play_episode | episode plugin url passed to `RunPlugin(url)` if list or `PlayMedia(url)` if string|

**Pull request closed without merging**
