### PR TITLE
Improving setting "TMDb artwork quality"

### PR DESCRIPTION
**Pull request by matke-84**
Ok. I didn't know that about posters. However, if you don't mind, I would do another PR. I think this really makes sense.

Original
Uses highest quality available.
Prefers fanart.tv artwork (if enabled and available)

High
Uses 1280x720 fanart from TMDb.
Prefers fanart.tv for all other artwork types (if enabled and available)
I actually fixed this. You wrote the above and you actually put the posters from TMDb and everything else from fanart.tv. Now it's actually as it should be, fanart from TMDb and everything else from fanart.tv. It makes a lot more sense considering that fanart images are the largest size. 

Medium - New
Uses 1280x720 fanart and 500x735 posters from TMDb.
Prefers fanart.tv for all other artwork types (if enabled and available)
In fact, this is the most optimal variant. Good performance with good looks. This makes special sense when you turn on the fanart.tv options.

Low
Uses 780x439 fanart and 342x502 posters from TMDb.
Prefers fanart.tv for all other artwork types (if enabled and available)
Best performance with slightly lower quality. Even in some views, lower quality is not noticed.

I hope you will accept this PR. :-)

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Excellent! Yes definitely agree with this approach as it adds an important option for when fanarttv is on. And good spotting about the poster/fanart blacklist being back to front.

**Comment by matke-84** [comment]
I also made similar changes for clearlogo. It works very well and has excellent performance. If you want I can do PR.

**Comment by matke-84** [comment]
Brother, you're fast on the trigger. :)

**Comment by jurialmunkey** [comment]
> I actually fixed this. You wrote the above and you actually put the posters from TMDb and everything else from fanart.tv. Now it's actually as it should be, fanart from TMDb and everything else from fanart.tv. It makes a lot more sense considering that fanart images are the largest size.

I decided to flip this back to 'posters' for high. With the your new medium option I think it gives more flexibility and makes the High setting a bit more optimal considering that multiple posters display on screen but there's only one fanart. 

On high, w1280 limit on fanart still applies for TMDb to prevent 4k images but it isn't forced so that there's still a way to get 1080p fanart from fanarttv.

**High**
Posters = w500 from TMDb
Thumbs = w1280 from TMDb
Fanart = w1920 from FanartTV and fallback to w1280 from TMDb

**Medium**
Posters = w500 from TMDb
Thumbs = w1280 from TMDb
Fanart = w1280 from TMDb

**Low**
Posters = w342 from TMDb
Thumbs = w780 from TMDb
Fanart = w780 from TMDb

**Comment by matke-84** [comment]
Yes it will open faster, but my idea was a little different. With high setting now the user loses the ability to change the poster. Why does I say this, the fanarts are now sorted out, but there are a lot of posters from tmdb that have a bunch of captions and we can't fix that, so I left the possibility on high setting to users change that and have decent performance again. I don’t know, I would bring back fanart, to leave that possibility on high. That's why I had the Very High option with previous PR, we can do that too, what do you think? 😀

**Comment by jurialmunkey** [comment]
> But there are a lot of posters from tmdb that have a bunch of captions and we can't fix that, so I left the possibility on high setting to users change that and have decent performance again.

You can get practically this same scenario using Original + FanartTV. All fanart on FanartTV is 1080p. There's only a small file size difference between 720p (~90kb at ~0.9 million pixels) and 1080p (~200kb at ~2 million pixels), so the download cost isn't that much. Plus 1080p fanart is actually better for cpu performance because there's no rescaling involved.

The size difference from 1080p to 4k (~1.6mb on TMDb) is huge because it goes from 2 million to 8 million pixels. Plus it's far more taxing for the cpu/gpu because that's an extra 6 million pixels that need to be rendered/rescaled.

**Comment by matke-84** [comment]
I'm thinking something now. I noticed that even if I turn off fanart.tv options and leave it to just pull artworks from TMDb, there is still the possibility of changing all artworks through the tmdb helper menu "select artwork". Is there a possibility then to just make a black list to show artworks from fanart.tv and leave the possibility of change through the menu "select artwork"?

**Comment by jurialmunkey** [comment]
> I'm thinking something now. I noticed that even if I turn off fanart.tv options and leave it to just pull artworks from TMDb, there is still the possibility of changing all artworks through the tmdb helper menu "select artwork". Is there a possibility then to just make a black list to show artworks from fanart.tv and leave the possibility of change through the menu "select artwork"?

At the moment it is difficult because of how the artwork cache is structured. But I'm working on something which will allow manually selecting artwork from both services and using that regardless of settings.

**Comment by matke-84** [comment]
@jurialmunkey 
I tried a new update. Great idea that now regardless of the option used, you can change the artwork. :-)
But I noticed a couple of bugs, so I'd like to tell you about them.
1. I saw that you have now implemented the option to choose fanarts and posters from both, fanart.tv and tmdb. You could also insert a clearlogo since we have them on both sites. :-)
2. When clearlogo on TV Shows changes, it doesn't change in seasons, episodes...
3. Also change of artworks doesn't work in seasons and episodes, in fact i think the problem here is that it pulls artwork from tmdb and tmdb has no artwork for seasons and episodes. I think fanart.tv must be the main source here for artwork manager. Maybe you can use both services only for fanarts because it is not specific for seasons and episodes.
That's what I've noticed so far, if I notice anything else I'm reporting.

**Comment by matke-84** [comment]
@jurialmunkey
And another little bug. If I go in to edit a poster in artwork manager, for example, and I want to go back, instead of returning me to the choice of another artwork, they close artwork manager completely.

**Comment by jurialmunkey** [comment]
@matke-84 - Thanks for testing. It was a fairly big change so I'm expecting some bugs for corner cases I forgot to test for. Please report any that you find and I'll try to fix.

Latest version _should_ fix the artwork properties not transferring properly from parent tvshow to season/episode. You _may_ need to re-select your artwork (or delete item cache from expert settings and restart Kodi to start from scratch) 

Latest version also adds clearlogos from TMDb and fixes the artwork manager back bug.

~I also noticed that season art isn't showing up from fanarttv at the moment and I haven't quite tracked down the issue yet. I must've made some small error somewhere as it is the same lookup method I was using before so it should work but clearly isn't The latest update will at least give season posters from TMDb~ 
**EDIT** Fixed now - should get options for season posters from both TMDb and FanartTV

**Comment by matke-84** [comment]
@jurialmunkey
The problem with seasons and episodes is also when I want to change some artwork they doesn't change it except posters in seasons. For example I have in my skin, in episodes level: episodes thumbnails, landscape picture of the season, and fanart in the background. I can't change season landscape picture and fanart, but I could with version 31.
Also landscape image from tmdb display with language.

**Comment by matke-84** [comment]
@jurialmunkey
With the latest version, poster and banner can be changed in the seasons, and nothing in the episodes.

**Comment by jurialmunkey** [comment]
@matke-84 - Okay I think in the latest version all the artwork inheritance issues should be fixed. 

Should be able to correctly select artwork and it should transfer correctly to the next level -- e.g. `poster` for tvshow becomes `tvshow.poster` for season/episode, and `poster` for season becomes `poster` for episodes.

**Comment by matke-84** [comment]
@jurialmunkey
Fanarts in seasons and episodes still can't be changed. It exists in the menu but when I select a change nothing happens. The rest, as far as I noticed, works.

**Comment by jurialmunkey** [comment]
@matke-84 - Ok hopefully *this* time it's working correctly. I finally realised what part I had back-to-front. Everything seems to be working correctly on my end as far as I can tell.

FYI - If you change artwork for an episode then it changes it for the entire season which is intentional - but the dialog should work properly now!

**Comment by matke-84** [comment]
@jurialmunkey
No, fanart image in seasons and episodes changes still don't work. What I noticed in relation to version 31 which is the latest version with the old artwork manager.
When I enter in seasons, each season had its own fanart. If I change the fanart for season 1, fanart in the episodes changes also, but if I change the fanart in the episodes for season 1, it will not change in the seasons. This makes sense to me.
I’ve also noticed when I’m in seasons and episodes artwork manger doesn’t show fanart from fanart.tv but only from tmdb. This happens with all settings. I deleted all cache.

**Comment by jurialmunkey** [comment]
@matke-84 Are you sure the skin you're using isn't point at Art(tvshow.fanart) instead of Art(fanart)? Can you test in Estuary to make sure it isn't a skin issue?  Also, please double check that you are actually running 4.5.40 - if installing from zip you need to make sure every zip has a unique name otherwise Kodi thinks you're installing an old version and uses its packages cache.

Also are the items you're testing also in your library? Because library artwork will _always_ override selected artwork if merge kodi db details is on.

It all works perfectly fine for me as shown in my debug overlay:

Here's a base tvshow where you can see the base artwork items
Honeyview_screenshot00233

Then here's seasons where you can see I have individualised season artwork plus the base show artwork has transferred
Honeyview_screenshot00234

And you can see in Episodes the same artwork is carrying across correctly
Honeyview_screenshot00235

Then I go back to seasons level and FanartTV artwork AND TMDb artwork show up for me:
Honeyview_screenshot00242

I change the season fanart and it changes correctly:
Honeyview_screenshot00238

And it transfers across to episodes too:
Honeyview_screenshot00239

I have tried so many different test scenarios to try to make it not work and it works correctly perfectly for me now. Even if I change quality it updates correctly to the new quality setting

**Comment by matke-84** [comment]
@jurialmunkey 
Big apology. You're right. I forgot to check skin code. Now works. Sorry again. I was just confused by how is worked with the old version but obviously the old version did it differently.
But I noticed one thing. For some TV Shows in seasons and episodes, the artwork manager does not give fanarts from fanart.tv but only from tmdb. Can you check: The Simpsons, Friends, The Flash (2014), Westworld...

**Comment by jurialmunkey** [comment]
> @jurialmunkey Big apology. You're right. I forgot to check skin code. Now works. Sorry again. I was just confused by how is worked with the old version but obviously the old version did it differently. But I noticed one thing. For some TV Shows in seasons and episodes, the artwork manager does not give fanarts from fanart.tv but only from tmdb. Can you check: The Simpsons, Friends, The Flash (2014), Westworld...

Before tvshow.fanart wasn't being filled properly in all cases so the skin you're using likely falls back to fanart only if tvshow.fanart is empty. The way it is now is how it should be though as it matches how artwork in Kodi's tvshow library works.

What seasons of those shows? Are you sure that fanarttv actually has season artwork available for those seasons? Note it only shows season specific artwork from fanarttv. You can see what artwork is available on the fanart.tv website

**Comment by matke-84** [comment]
@jurialmunkey
That's why I ask. Fanart or background as it is called on fanart.tv doesn't exist for seasons or episodes. Shouldn't all fanarts appear in all TV Shows for seasons and episodes? So I asked about these couple of tv shows, I don't know why it appears in some and not in others.

**Comment by jurialmunkey** [comment]
> @jurialmunkey That's why I ask. Fanart or background as it is called on fanart.tv doesn't exist for seasons or episodes. Shouldn't all fanarts appear in all TV Shows for seasons and episodes? So I asked about these couple of tv shows, I don't know why it appears in some and not in others.

Actually it does provide a season value for backgrounds via the API. You're correct however that it isn't that clear on the website itself.

e.g. here's the output for Euphoria for `showbackground`. You can see the season values - some have specific seasons and others are 'all". I could make a change to also include 'all' in the lookup.

```json
"showbackground": [
    {
      "id": "112884",
      "url": "https://assets.fanart.tv/fanart/tv/360261/showbackground/euphoria-2019-5ec8c687b827b.jpg",
      "lang": "",
      "likes": "2",
      "season": "1"
    },
    {
      "id": "144184",
      "url": "https://assets.fanart.tv/fanart/tv/360261/showbackground/euphoria-2019-61f796e4b3aef.jpg",
      "lang": "",
      "likes": "2",
      "season": "all"
    },
    {
      "id": "144188",
      "url": "https://assets.fanart.tv/fanart/tv/360261/showbackground/euphoria-2019-61f7991f10789.jpg",
      "lang": "",
      "likes": "2",
      "season": "2"
    },
    {
      "id": "133848",
      "url": "https://assets.fanart.tv/fanart/tv/360261/showbackground/euphoria-2019-61344b8cb197f.jpg",
      "lang": "",
      "likes": "0",
      "season": "0"
    },
    {
      "id": "133850",
      "url": "https://assets.fanart.tv/fanart/tv/360261/showbackground/euphoria-2019-61344c12e2750.jpg",
      "lang": "",
      "likes": "0",
      "season": "0"
    },
    {
      "id": "143663",
      "url": "https://assets.fanart.tv/fanart/tv/360261/showbackground/euphoria-2019-61ec7aef670fa.jpg",
      "lang": "",
      "likes": "0",
      "season": "2"
    }
  ],
```

**Comment by matke-84** [comment]
@jurialmunkey
Great that you put on all fanarts. I just don't think any fanart is specific to any season, so possibility of choice is good option.
I think we now have an almost perfect artwork manager and the way how artworks are displayed. Good job my friend.
Now it remains to try to improve the process of entering in all lists. Today I will try to do tests for seasons and episodes, so I will upload log like last time.

**Comment by matke-84** [comment]
@jurialmunkey
Something went wrong with the last update. It pulls everything from tmdb instead of fanart.tv and tmdb.

**Comment by jurialmunkey** [comment]
> @jurialmunkey Something went wrong with the last update. It pulls everything from tmdb instead of fanart.tv and tmdb.

~Do you mean in the artwork manager? Because I can select FanartTV there.~ Actually yep I see what you mean, fix incoming.

**Comment by jurialmunkey** [comment]
> @jurialmunkey Something went wrong with the last update. It pulls everything from tmdb instead of fanart.tv and tmdb.

Accidentally deleted an important line there! Should be fixed now ^^^

**Comment by matke-84** [comment]
> > @jurialmunkey Something went wrong with the last update. It pulls everything from tmdb instead of fanart.tv and tmdb.
> 
> Accidentally deleted an important line there! Should be fixed now ^^^

Yes, it's ok now.

**Comment by matke-84** [comment]
@jurialmunkey
One little thing. Set for seasons when there are no posters on fanart.tv for some specific to pull from tmdb. I guess it should set up also vice versa, tmdb>fanart.tv.
Example: The Simpsons, Seasone 32, TMDb artwork quality Original, turn on Fanart.tv settings.

**Comment by jurialmunkey** [comment]
> 

^^^ That should fix it. I think it probably only matters for posters as that's really the only season specific artwork TMDb has.

**Comment by matke-84** [comment]
@jurialmunkey
Yes, I also think only posters are season specific.

**Comment by matke-84** [comment]
@jurialmunkey
Can you check how trakt popular and trending lists are working for you? It seems to me like they broke in tmdb helper. They only have two pages, I can't play a movie... I also tried with Kodi default skin.

**Pull request merged**
